// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
)

type Order struct {
	ID          int32
	UserName    sql.NullString
	ProductName sql.NullString
	Amount      int32
}
